name: opakuStore
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  flutter_inappwebview: ^4.0.0+4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^1.0.2
  flutter_datetime_picker: ^1.3.4
  font_awesome_flutter: ^8.7.0
  carousel_slider: ^2.0.0
  flutter_masked_text: ^0.8.0
  device_preview: ^0.3.0+1
  flutter_rating_bar: ^3.0.1+1
  auto_size_text: ^2.1.0
  flutter_credit_card: 0.1.3
  validators: ^2.0.0+1
  shared_preferences: ^0.5.6+3
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.6
  crypto: ^2.1.3
  multi_image_picker: ^4.6.5+rc.1
  grouped_buttons: ^1.0.4
  uuid: ^2.0.4
  firebase_storage: ^3.1.5
  cached_network_image: ^2.1.0+1
  photo_view: ^0.9.2
  progress_dialog: ^1.2.1
  flutter_slidable: ^0.5.4
  flutter_google_places: ^0.2.5
  google_maps_webservice: ^0.0.17
  google_maps_flutter: ^0.5.30
  #google_maps_flutter: ^0.0.3
  intl: ^0.16.1
  stripe_payment: ^1.0.7
  cloud_functions: ^0.4.2+3
  charts_flutter: ^0.9.0
  fl_chart: ^0.9.3
  http: ^0.12.0+4
  firebase_analytics: any
flutter_cupertino_date_picker:
  git:
    url: https://github.com/develeenew/flutter_cupertino_date_picker.git
dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "lib/src/assets/images/launcher_logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/images/
    - lib/src/assets/index.html
    - lib/src/assets/index.js
    - lib/src/assets/index.css


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
